$fname = Read-Host "Enter file name/path(with extension) "
$cert = New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -Type CodeSigningCert -Subject "PowerShell Code Signing"
Get-ChildItem -Path Cert:\CurrentUser\My | ? Subject -EQ "CN=PowerShell Code Signing"
Move-Item -Path $cert.PSPath -Destination "Cert:\CurrentUser\Root"
Set-AuthenticodeSignature -FilePath $Fname -Certificate $cert
# SIG # Begin signature block
# MIIFhQYJKoZIhvcNAQcCoIIFdjCCBXICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUR0gNhhvreV/s4JtzR3CY25rs
# aM6gggMYMIIDFDCCAfygAwIBAgIQU8vYshT137NKF/mVrr2oCjANBgkqhkiG9w0B
# AQsFADAiMSAwHgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZzAeFw0yMDEy
# MDIxNTU1MzhaFw0yMTEyMDIxNjE1MzhaMCIxIDAeBgNVBAMMF1Bvd2VyU2hlbGwg
# Q29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAucMl
# Rbd5AAV7R4zv+qp+gjCZIH6LR5zQXWrnKSD10eR5PhY8xK3g5otwCvdGvrNsRSBL
# Qmgtquc9iovIgoNbvlRtbRUDex+uLUIpRzvft+5ApV72h6NUZDUwOxDHKsJ4wqg4
# hWanWXz9/0aRKiOsosdzqxOwnc1YomfMHQmblo0dosfywM1IXO3OyIYPZmXkIMB9
# yszt9+VCILKVHsypkWOcLzpdIVlYhOUK5TZJEcoWJpu4kkYFliO/eA2vTo6xld9H
# /VZ+Q5kSoNljtQjfMEYon6LfxWU1q2UYTSUvz+hCcGF7LlCFxLJ3FSQ5E8bo4MLB
# 56XmB7zZQAiPyJ5+yQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFGEqlLWf8Mhg3XK4ol+ompog/Hq5MA0GCSqG
# SIb3DQEBCwUAA4IBAQAr4BU55T4Ed1FDZC1W/rQ0lcCXpzgTIFojqicnOmA+snek
# xlw3MBCYJ4CtSY4LIT6XSnx1B+0bvYFyUHGnx96w/CHwnnBki/hOZG5bjI6qjd5V
# KgKRTHRag8u+fVgkpzwPZOQDlkhhNWc6q0u6bHeOXN1oWk6JAuyCtcq5Jf1oo26s
# bbPZ1TBXKQADesUpZt5Bh1r69SXrwPSMp4MIUZLToR60jREKrwdNv3iQ0KicIP2Y
# 81nfG6q2iYo1m3e+gGcx/W1FgbaAkTiUmFakGtLNT8jh1SMEMr4eLocqjzVa3GEV
# c0EoMdI4YOXJhQMKYg7KHG3El5RVW3ho+kzpk5QSMYIB1zCCAdMCAQEwNjAiMSAw
# HgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZwIQU8vYshT137NKF/mVrr2o
# CjAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQUkCMW51Q7+OsKZ741VCFq48qxjvEwDQYJKoZIhvcN
# AQEBBQAEggEAoHVVr/WTKO4jUIYMpAvSNo14cfE4JJGzz0bQPWz4kgOu5gOc6pO0
# ksSVNIHHHeTW2lqNP+R+eCSCrNCNwbKlJ6F2bo1SCIDOJBpxZg9iTACCFetCJv+d
# nnvjE0Nc3KYfqmwsl4iq7JL0UFUIY9TX3YqHI17EvxP32duDL+4UcDzIJoSwkWfn
# THnxVmmkC8a3BzSqoHIX+P8gpqlJu4WV6wyFaJMgc1xdP+rQGDod85Ktqjt8UwwM
# Rsm6lZ59IM+UjXkZKxnus/zAqp2YhhQY+/9BvOmD8eA1zx7VJGJ+SHQVFE2z6G+u
# 5kwk9WUSgEWea6HYyzA+DcK5VzVG0nSO4g==
# SIG # End signature block
